# Set the current version of compose yml file
version: "3"

services:
  Server:
    image: ioa-server:latest
    build:
      context: ../../
      dockerfile: dockerfiles/server.Dockerfile
    container_name: ioa-server
    volumes:
      - ../../configs/server_configs:/app/configs
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY
    ports:
      - 7788:7788
    stdin_open: true
    tty: true

  Agent1:
    image: ioa-client:latest
    build:
      context: ../../
      dockerfile: dockerfiles/client.Dockerfile
    container_name: react-agent-1
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../configs/client_configs:/app/configs
    environment:
      - OPENAI_API_KEY
    ports:
      - 5050:5050
    depends_on:
      - Server
    stdin_open: true
    tty: true

  # Agent2:
  #   image: ioa-client:latest
  #   build:
  #     context: ../../
  #     dockerfile: dockerfiles/client.Dockerfile
  #   container_name: react-agent-2
  #   env_file:
  #     - .env
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - ../../configs/client_configs:/app/configs
  #   environment:
  #     - OPENAI_API_KEY
  #   ports:
  #     - 5051:5050
  #   depends_on:
  #     - Server
  #   stdin_open: true
  #   tty: true

  ServerFrontend:
    image: ioa-server-frontend:latest
    build:
      context: ../../
      dockerfile: dockerfiles/server_frontend.Dockerfile
    container_name: server_frontend
    ports:
      - 80:80
    depends_on:
      - Server
    stdin_open: true
    tty: true

networks:
  default:
    name: agent_network
    driver: bridge
    external: true
