# Set the current version of compose yml file
version: "3"

services:
  Server:
    image: ioa-server:latest
    build:
      context: ../../
      dockerfile: dockerfiles/server.Dockerfile
    container_name: ioa-server
    env_file:
      - .env
    volumes:
      - ./volumes/sqlite:/app/database
      - ../../configs/server_configs:/app/configs
    ports:
      - 7788:7788
    stdin_open: true
    tty: true

  WebBrowser:
    image: ioa-client:latest
    build:
      context: ../../
      dockerfile: dockerfiles/client.Dockerfile
    container_name: web_browser
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/sqlite:/app/database
      - ./volumes/openai_response_log:${OPENAI_RESPONSE_LOG_PATH}
      - ../../configs/client_configs:/app/configs
    environment:
      - CUSTOM_CONFIG=configs/cases/gaia/web_browser.yaml
    ports:
      - 5050:5050
    depends_on:
      - Server
    stdin_open: true
    tty: true

  CodeExecutor:
    image: ioa-client:latest
    build:
      context: ../../
      dockerfile: dockerfiles/client.Dockerfile
    container_name: code_executor
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/sqlite:/app/database
      - ./volumes/openai_response_log:${OPENAI_RESPONSE_LOG_PATH}
      - ../../configs/client_configs:/app/configs
    environment:
      - CUSTOM_CONFIG=configs/cases/gaia/code_executor.yaml
    ports:
      - 5051:5050
    depends_on:
      - Server
    stdin_open: true
    tty: true

  YouTube:
    image: ioa-client:latest
    build:
      context: ../../
      dockerfile: dockerfiles/client.Dockerfile
    container_name: youtube
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/sqlite:/app/database
      - ./volumes/openai_response_log:${OPENAI_RESPONSE_LOG_PATH}
      - ../../configs/client_configs:/app/configs
    environment:
      - CUSTOM_CONFIG=configs/cases/gaia/youtube.yaml
    ports:
      - 5052:5050
    depends_on:
      - Server
    stdin_open: true
    tty: true

  Wikidata:
    image: ioa-client:latest
    build:
      context: ../../
      dockerfile: dockerfiles/client.Dockerfile
    container_name: wikidata
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/sqlite:/app/database
      - ./volumes/openai_response_log:${OPENAI_RESPONSE_LOG_PATH}
      - ../../configs/client_configs:/app/configs
    environment:
      - CUSTOM_CONFIG=configs/cases/gaia/wikidata.yaml
    ports:
      - 5053:5050
    depends_on:
      - Server
    stdin_open: true
    tty: true

  ServerFrontend:
    image: ioa-server-frontend:latest
    build:
      context: ../../
      dockerfile: dockerfiles/server_frontend.Dockerfile
    container_name: server_frontend
    ports:
      - 80:80
    depends_on:
      - Server
    stdin_open: true
    tty: true

networks:
  default:
    name: agent_network
    external: true
