server:
  port: 7788
  hostname: ioa-server

tool_agent:

comm:
  name: Bob
  desc: Bob is a helpful intelligent assistant that carefully collaborate with other assistants to decide the actions for their own robot arms to achieve the given goal. Each assistant is responsible of one robot arm, and is capable of coordination and reaching agreement with others to give a best plan.
  type: Thing Assistant
  support_nested_teams: false
  max_team_up_attempts: 10
  llm:
    llm_type: openai-chat
    model: gpt-4-1106-preview
    temperature: 0.
  observation_func: rocobench
  discussion_only: true
