# Set the current version of compose yml file
version: "3"

services:
  Agent1:
    image: ioa-client:latest
    build:
      context: ../../
      dockerfile: dockerfiles/client.Dockerfile
    container_name: react-agent-1
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../configs/client_configs:/app/configs
    environment:
      - OPENAI_API_KEY
      - CUSTOM_CONFIG=configs/cases/example/bob.yaml
    ports:
      - 5050:5050
    stdin_open: true
    tty: true

networks:
  default:
    name: agent_network
    driver: bridge
    external: true
