# Set the current version of compose yml file
version: "3"

services:
  Server:
    image: ioa-server:latest
    build:
      context: ../../
      dockerfile: dockerfiles/server.Dockerfile
    container_name: ioa-server
    env_file:
      - .env
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/sqlite:/app/database
      - ../../configs/server_configs:/app/configs
    environment:
      - OPENAI_API_KEY
    ports:
      - 7788:7788
    stdin_open: true
    tty: true

  WeizeChen:
    image: ioa-client:latest
    build:
      context: ../../
      dockerfile: dockerfiles/client.Dockerfile
    container_name: weize
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/sqlite:/app/database
      - ./volumes/openai_response_log:${OPENAI_RESPONSE_LOG_PATH}
      - ../../configs/client_configs:/app/configs
    environment:
      - OPENAI_API_KEY
      - CUSTOM_CONFIG=configs/cases/paper_writing/weizechen.yaml
    ports:
      - 5050:5050
    depends_on:
      - Server
    stdin_open: true
    tty: true

  ChenQian:
    image: ioa-client:latest
    build:
      context: ../../
      dockerfile: dockerfiles/client.Dockerfile
    container_name: chenqian
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/sqlite:/app/database
      - ./volumes/openai_response_log:${OPENAI_RESPONSE_LOG_PATH}
      - ../../configs/client_configs:/app/configs
    environment:
      - OPENAI_API_KEY
      - CUSTOM_CONFIG=configs/cases/paper_writing/chenqian.yaml
    ports:
      - 5051:5050
    depends_on:
      - Server
    stdin_open: true
    tty: true

  ChengYang:
    image: ioa-client:latest
    build:
      context: ../../
      dockerfile: dockerfiles/client.Dockerfile
    container_name: chengyang
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/sqlite:/app/database
      - ./volumes/openai_response_log:${OPENAI_RESPONSE_LOG_PATH}
      - ../../configs/client_configs:/app/configs
    environment:
      - OPENAI_API_KEY
      - CUSTOM_CONFIG=configs/cases/paper_writing/chengyang.yaml
    ports:
      - 5052:5050
    depends_on:
      - Server
    stdin_open: true
    tty: true

  Arxiv:
    image: ioa-client:latest
    build:
      context: ../../
      dockerfile: dockerfiles/client.Dockerfile
    container_name: arxiv
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/sqlite:/app/database
      - ./volumes/openai_response_log:${OPENAI_RESPONSE_LOG_PATH}
      - ../../configs/client_configs:/app/configs
    environment:
      - OPENAI_API_KEY
      - OPENAI_BASE_URL
      - CUSTOM_CONFIG=configs/cases/paper_writing/arxiv.yaml
    ports:
      - 5053:5050
    depends_on:
      - Server
    stdin_open: true
    tty: true

  ServerFrontend:
    image: ioa-server-frontend:latest
    build:
      context: ../../
      dockerfile: dockerfiles/server_frontend.Dockerfile
    container_name: server_frontend
    ports:
      - 80:80
    depends_on:
      - Server
    stdin_open: true
    tty: true

networks:
  default:
    name: agent_network
    external: true
    # driver: bridge
