# Set the current version of compose yml file
version: "3"

services:
  Server:
    image: ioa-server:latest
    build:
      context: ../../
      dockerfile: dockerfiles/server.Dockerfile
    container_name: ioa-server
    volumes:
      - ../../configs/server_configs:/app/configs
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY
      #- OPENAI_BASE_URL
    ports:
      - 7788:7788
    stdin_open: true
    tty: true

  Alice:
    image: ioa-client:latest
    build:
      context: ../../
      dockerfile: dockerfiles/client.Dockerfile
    container_name: alice
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY
      #- OPENAI_BASE_URL
      - CUSTOM_CONFIG=configs/cases/rocobench/alice.yaml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../configs/client_configs:/app/configs
    ports:
      - 5050:5050
    depends_on:
      - Server
    stdin_open: true
    tty: true

  # WeizeChenFrontend:
  #   image: ioa-frontend:latest
  #   build:
  #     context: ../../
  #     dockerfile: dockerfiles/frontend.Dockerfile
  #   container_name: weize_frontend
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - WeizeChen
  #   stdin_open: true
  #   tty: true

  Bob:
    image: ioa-client:latest
    build:
      context: ../../
      dockerfile: dockerfiles/client.Dockerfile
    container_name: bob
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../configs/client_configs:/app/configs
    environment:
      - OPENAI_API_KEY
      #- OPENAI_BASE_URL
      - CUSTOM_CONFIG=configs/cases/rocobench/bob.yaml
    ports:
      - 5051:5050
    depends_on:
      - Server
    stdin_open: true
    tty: true

  Chad:
    image: ioa-client:latest
    build:
      context: ../../
      dockerfile: dockerfiles/client.Dockerfile
    container_name: chad
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../configs/client_configs:/app/configs
    environment:
      - OPENAI_API_KEY
      #- OPENAI_BASE_URL
      - CUSTOM_CONFIG=configs/cases/rocobench/chad.yaml
    ports:
      - 5052:5050
    depends_on:
      - Server
    stdin_open: true
    tty: true

  Dave:
    image: ioa-client:latest
    build:
      context: ../../
      dockerfile: dockerfiles/client.Dockerfile
    container_name: dave
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../configs/client_configs:/app/configs
    environment:
      - OPENAI_API_KEY
      #- OPENAI_BASE_URL
      - CUSTOM_CONFIG=configs/cases/rocobench/dave.yaml
    ports:
      - 5053:5050
    depends_on:
      - Server
    stdin_open: true
    tty: true

  ServerFrontend:
    image: ioa-server-frontend:latest
    build:
      context: ../../
      dockerfile: dockerfiles/server_frontend.Dockerfile
    container_name: server_frontend
    ports:
      - 80:80
    depends_on:
      - Server
    stdin_open: true
    tty: true

networks:
  default:
    name: agent_network
    external: true
    # driver: bridge
