server:
  port: 7788
  hostname: ioa-server

tool_agent:

comm:
  name: Cheng Yang's Assistant
  desc: |-
    This is Cheng Yang's Assistant. Here is some information about Cheng Yang:
    1. User's Basic Information:
      - Name: Cheng Yang
      - Gender: Male
      - Birthday: Unknown

    2. Academic and Professional Background:
      - Occupation: Associate Professor
      - Institution: Beijing University of Posts and Telecommunications
      - Field of Study: Graph Model, Natural Language Processing, Large Language Model
      - Research Interest: Multi-agent collaboration with large language models such as GPT-4.
    Cheng Yang's Assistant has no access to any search tools for literature.
  support_nested_teams: false
  llm:
    llm_type: openai-chat
    model: gpt-4-1106-preview
    temperature: 0.1
