minicpm-embedding-light:
  model_id: Openbmb/MiniCPM-Embedding-Light
  model_type: embedding

minicpm-reranker-light:
  model_id: Openbmb/MiniCPM-Reranker-Light
  model_type: reranker

MiniCPM3-4B:
  model_id: Openbmb/MiniCPM3-4B
  model_type: llm

